; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = GPAD_API
default_envs = esp32dev

[env:native]
platform = native
build_flags = -std=gnu++11

[env:esp32dev]
extra_scripts = 
	pre:pre_extra_script.py
build_flags = 
	-Os
	-ffunction-sections
	-fdata-sections
	-Wl,--gc-sections
	-DDEBUG_LEVEL=0
	-DELEGANTOTA_USE_ASYNC_WEBSERVER=1
platform = espressif32@^6.12.0
board = esp32dev
board_build.filesystem = littlefs
# upload_port = COM22 #One of Lee's Ports.
monitor_speed = 115200
monitor_echo = yes
framework = arduino
lib_deps = 
	mathertel/RotaryEncoder@^1.5.3
	knolleary/PubSubClient@^2.8
	neu-rah/ArduinoMenu library@^4.21.5
	cygig/DailyStruggleButton@^0.5.1
	neu-rah/streamFlow@0.0.0-alpha+sha.bf16ce8926
	dfrobot/DFRobotDFPlayerMini@^1.0.6
	tzapu/WiFiManager@^2.0.17
	ayushsharma82/ElegantOTA@^3.1.7
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
lib_ignore =
	mocking
test_ignore = native/*
